### ISSUE TITLE
Which license is this project using?

### ISSUE THREAD

**Issue by ambroisie** [evdenis/cvehound#22]
According to `LICENSE` it is GPLv3.

According to `setup.py` it is GPLv2.

Finally, is it supposed to be GPLv{2,3} only, or also any later version?

**Comment by evdenis** [comment]
GPLv3 for python code, but all .cocci rules (https://github.com/evdenis/cvehound/tree/master/cvehound/cve) are GPLv2 because detection rules reuse chunks of Linux kernel code. Sorry about this mess, I'll add a clarification in the README.md

**Comment by evdenis** [comment]
> Finally, is it supposed to be GPLv{2,3} only, or also any later version?

What is your use case? Do you need other license?

**Comment by ambroisie** [comment]
> What is your use case? Do you need other license?

I am packaging this for NixOS, which makes a difference between `gpl3Only` and `gpl3Plus`.

**Comment by evdenis** [comment]
`gpl3Only`. If there will be newer versions of the license it will be more safe to relicense the project after. I reuse parts of the undertaker project (https://vamos.informatik.uni-erlangen.de/trac/undertaker) (GPLv3) to analyse kernel config files (--config option)

**Comment by evdenis** [comment]
Oh, sorry undertaker is `GPLv3 or later`. Anyway, I think gpl3Only is more safe as by now.

**Comment by ambroisie** [comment]
Alright, thank you for your time.

I'll let you close this issue once you're done with any changes you might want to make relating to it.

**Comment by evdenis** [comment]
Thank you for packaging the project. Feel free to request changes or report issues if something doesn't work on `NixOS`.

**Comment by evdenis** [comment]
Closed with https://github.com/evdenis/cvehound/commit/0c1f82a1da642e0b7e9235398f6ecd14e1efd297

**Comment by vt-alt** [comment]
BTW. GPL-2.0-only and GPL-3.0-or-later are incompatible between each other. https://gplv3.fsf.org/wiki/index.php/Compatible_licenses#GPLv3-incompatible_licenses

**Comment by evdenis** [comment]
I don't think there is a conflict in the project. *.cocci files are under GPLv2 because they reuse parts of a kernel code, everything else in the project is GPLv3.
