### ISSUE TITLE
making data directory for storing kernel_cves.json.gz configurable

### ISSUE THREAD

**Issue by armijnhemel** [evdenis/cvehound#31]
Would it be possible to make the directory for storing `kernel_cves.json.gz` configurable?

**Comment by evdenis** [comment]
Yes, it's possible. Currently, I rely on pkg_resources 
```
def get_cves_metadata():
    cves = pkg_resources.resource_filename('cvehound', 'data/kernel_cves.json.gz')
    data = None
    with gzip.open(cves, 'rt', encoding='utf-8') as fh:
        data = json.load(fh)
    return data
 ```
What do you think will work for you best? `CVEHOUND_METADATA` env var, `--metadata` arg, install paths preprocessing during installation (probably there are some examples in NixOS repos), something else?

**Comment by armijnhemel** [comment]
> Yes, it's possible. Currently, I rely on pkg_resources
> 
> ```
> def get_cves_metadata():
>     cves = pkg_resources.resource_filename('cvehound', 'data/kernel_cves.json.gz')
>     data = None
>     with gzip.open(cves, 'rt', encoding='utf-8') as fh:
>         data = json.load(fh)
>     return data
> ```
> 
> What do you think will work for you best? `CVEHOUND_METADATA` env var, `--metadata` arg, install paths preprocessing during installation (probably there are some examples in NixOS repos), something else?

A command line option, a setting in a configuration file, or an environment variable would all be fine. Currently it is hard for me as NixOS adds the data in a read only part (which is read only for a reason namely that it is immutable). Another option would be to put the data into a separate package. Whatever is the easiest for you :-)

**Comment by evdenis** [comment]
Please, review #34. Is it enough to solve your problem?

**Comment by armijnhemel** [comment]
> Please, check #34. Is it enough to solve your problem?

Yes, thank you!
